"""
Physical parameters for a quadrotor. Values parameterize the inertia, motor dynamics,
rotor aerodynamics, parasitic drag, and rotor placement.
Additional sources:
    https://bitcraze.io/2015/02/measuring-propeller-rpm-part-3
    https://wiki.bitcraze.io/misc:investigations:thrust
    https://commons.erau.edu/cgi/viewcontent.cgi?article=2057&context=publication
    "Data-Driven System Identification of Quadrotors Subject to Motor Delays", Eschmann et al. 2024. https://arxiv.org/abs/2404.07837
Notes:
    k_thrust is inferred from 14.5 g thrust at 2500 rad/s
    k_drag is mostly made up
"""
import numpy as np

d = 0.043  # Arm length

quad_params = {

    # Inertial properties
    #   mass
    #   inertial matrix
    #       higher value means it is harder to rotate at that axis
    'mass': 0.03,       # kg
    'Ixx':  1.43e-5,    # kg*m^2
    'Iyy':  1.43e-5,    # kg*m^2
    'Izz':  2.89e-5,    # kg*m^2
    'Ixy':  0.0,        # kg*m^2
    'Iyz':  0.0,        # kg*m^2
    'Ixz':  0.0,        # kg*m^2

    # Geometric properties, all vectors are relative to the center of mass.
    #   Number of rotors and their positions (x,y,z) in the body frame
    'num_rotors': 4,                        # for looping over each actuator
    'rotor_pos': {
                    'r1': d*np.array([ 0.70710678118, 0.70710678118, 0]),    # Location of Rotor 1, meters
                    'r2': d*np.array([ 0.70710678118,-0.70710678118, 0]),    # Location of Rotor 2, meters
                    'r3': d*np.array([-0.70710678118,-0.70710678118, 0]),    # Location of Rotor 3, meters
                    'r4': d*np.array([-0.70710678118, 0.70710678118, 0]),    # Location of Rotor 4, meters
                 },

    # Each motor's spin direction, [clockwise, counter-clockwise]
    'rotor_directions': np.array([1,-1,1,-1]),  # This dictates the direction of the torque for each motor.

    'rI': np.array([0,0,0]), # location of the IMU sensor, meters

    # Frame aerodynamic properties
    #   aerodynamic drag cofficients
    #       higher value means more aerodynamic resistance along that axis (need more power to move the vehilce along that axis)
    'c_Dx': 0.0,  # parasitic drag in body x axis, N/(m/s)**2
    'c_Dy': 0.0,  # parasitic drag in body y axis, N/(m/s)**2
    'c_Dz': 0.0,  # parasitic drag in body z axis, N/(m/s)**2

    # Rotor properties (the propeller)
    # See "System Identification of the Crazyflie 2.0 Nano Quadrocopter", Forster 2015.
    #   k_eta: A lumped aerodynamic parameter. (Vertical lift)
    #          Thrust = k_eta * w^2
    #   k_m: How strongly the rotor resists spinning, producing a torque around the vertical axis. (Yaw control)
    #        M_yaw = k_m * rotor_speed^2 * rotor_direction
    #   k_d: Lumps the rotor-plane drag coming from blade aerodynamics. (Lateral disturbance)
    #        H = - rotor_speed * (rotor_drag_matrix @ local_airspeed)
    #   k_z: The downwash component from the properller. Higher value causes the drone to lift harder. (Vertical drag effect)
    #   k_h: Represents the increase of thrust during forward flight (similar to helicopter translational lift). (Extra lift in forward flight)
    #        Translational lift = k_h * (local_airspeed_x² + local_airspeed_y²)
    #   k_flap: The moment generated by the tilt of the rotor due to flapping (Rotational moment disturbances)
    #   rotor_speed_min and rotor_speed_max enforce(simplfy) physical of the ESC+motor system
    'k_eta': 2.3e-08,           # thrust coefficient N/(rad/s)**2
    'k_m':   7.8e-10,           # yaw moment coefficient Nm/(rad/s)**2
    'k_d':   10.2506e-07,       # rotor drag coefficient N/(rad*m/s**2) = kg/rad
    'k_z':   7.553e-07,         # induced inflow coefficient N/(rad*m/s**2) = kg/rad
    'k_h':   0.0,               # translational lift coefficient (N/(m/s)**2) = kg/m
    'k_flap': 0.0,              # Flapping moment coefficient Nm/(rad*m/s**2) = kg*m/rad

    # Motor properties
    'tau_m': 0.072,           # motor response time, seconds
    'rotor_speed_min': 0,       # rad/s
    'rotor_speed_max': 2500,    # rad/s

    # Motor properties
    #   tau_m: Motor time constant (motor response speed).
    #          How quickly the motor reaches a new rotor speed when commanded.
    #   motor_noise_std: Noise in rotor speed
    #                    This adds Gaussian noise to the actual rotor speed after each integration step.
    #                    state['rotor_speeds'] += np.random.normal(scale=motor_noise_std)
    'tau_m': 0.005,           # motor response time, seconds
    'motor_noise_std': 0.0,     # rad/s

    # Lower level controller properties (for higher level control abstractions)
    'k_w': 200,               # The body rate P gain (for cmd_ctbr)
    'k_v': 10,              # The *world* velocity P gain (for cmd_vel)
    'kp_att': 1030,      # The attitude P gain (for cmd_vel, cmd_acc, and cmd_ctatt)
    'kd_att': 51,       # The attitude D gain (for cmd_vel, cmd_acc, and cmd_ctatt)

}
